FROM ubuntu:xenial
RUN sed -i "s/http:\/\/archive.ubuntu.com/http:\/\/mirrors.tuna.tsinghua.edu.cn/g" /etc/apt/sources.list && \
    apt-get update && apt-get -y dist-upgrade && \
    DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata && \
    apt-get install -y apt-utils net-tools && \
    apt-get install -y openssh-server && \
    apt-get install -y zsh sudo curl fonts-powerline && \
    apt-get install -y git && \
    apt-get install -y bsdmainutils netcat-traditional inetutils-ping && \
    apt-get install -y ltrace strace && \
    apt-get install -y make gcc

RUN ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

RUN mkdir -p ~/.pip && echo "[global]\nindex-url = https://repo.huaweicloud.com/repository/pypi/simple\ntrusted-host = repo.huaweicloud.com\ntimeout = 120" > ~/.pip/pip.conf

# Install python2, pip2, pwntools
RUN apt-get install -y python python-dev \
    && wget -P ~/pip2 https://bootstrap.pypa.io/pip/2.7/get-pip.py \
    && python ~/pip2/get-pip.py \
    && pip2 install --upgrade pip \
    && pip2 install --upgrade pwntools \
    && pip2 install pathlib2

RUN apt-get install -y python3 python3-pip \
    && wget -P ~/pip3 https://bootstrap.pypa.io/pip/3.5/get-pip.py \
    && python3 ~/pip3/get-pip.py \
    && pip3 install --upgrade pip \
    && apt-get install -y libffi-dev -y \
    && pip3 install --upgrade pwntools

RUN git clone https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh
RUN cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc
RUN git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
RUN git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
RUN sed -i "s/plugins=(git)/plugins=(git zsh-autosuggestions zsh-syntax-highlighting)/g" ~/.zshrc

RUN git clone https://github.com/chxuan/vimplus.git ~/.vimplus
RUN cd ~/.vimplus && ./install.sh
RUN cd ~/.vim/plugged/YouCompleteMe && python3 install.py --clang-completer


#RUN git clone https://github.com/pwndbg/pwndbg.git ~/pwndbg
#RUN cd ~/pwndbg && ./setup.sh

RUN git clone https://github.com/scwuaptx/Pwngdb.git ~/Pwngdb
RUN cp ~/Pwngdb/.gdbinit ~/
RUN sed -i "s@source ~/peda/peda.py@source ~/pwndbg/gdbinit.py@g" ~/.gdbinit 

RUN apt-get install -y tmux
RUN echo "set-option -g mouse on" > ~/.tmux.conf

# Run 32-bit ELF
RUN apt-get install -y libc6-dev-i386

# Install glibc debugging info
RUN apt-get install -y libc6-dbg && \
    dpkg --add-architecture i386 && \
    apt-get update && \
    apt-get install -y libc6-dbg:i386

# Install ropgadget, one_gadget, seccomp-tools
RUN apt-get install -y software-properties-common python-software-properties && \
    add-apt-repository -y ppa:brightbox/ruby-ng && \
    apt-get update && apt-get install -y ruby2.6 ruby2.6-dev

RUN pip3 install ropgadget && \
    gem install one_gadget seccomp-tools

RUN pip3 install z3-solver angr keystone-engine lief
RUN pip2 install z3-solver keystone-engine

# update pwntools to newest
RUN git clone --depth 1 https://github.com/Gallopsled/pwntools.git ~/pwntools \
    && pip2 install --upgrade ~/pwntools \
    && pip3 install --upgrade ~/pwntools \
    && echo "[update]\ninterval=never" > ~/.pwn.conf

RUN apt-get install -y autoconf automake libtool
#RUN git clone https://github.com/NixOS/patchelf.git ~/patchelf && \
#    cd ~/patchelf && ./bootstrap.sh && ./configure && make && make install

# Install glibc source
WORKDIR /root
RUN sed -i "s/# deb-src http:\/\/mirrors.tuna.tsinghua.edu.cn/deb-src http:\/\/mirrors.tuna.tsinghua.edu.cn/g" /etc/apt/sources.list && \
    apt-get update && \
    apt-get source libc6-dev

RUN echo "let g:ycm_global_ycm_extra_conf = '~/.ycm_extra_conf.py'" >> ~/.vimrc

#COPY --from=wuhouxiaoqi/glibc_docker /glibc /glibc

RUN apt-get update
RUN apt-get install -y gcc-arm-linux-gnueabi gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu
RUN apt-get install -y gcc-mips-linux-gnu gcc-mips64-linux-gnuabi64 gcc-mips64el-linux-gnuabi64 gcc-mipsel-linux-gnu
RUN apt-get install -y qemu qemu-user-static
RUN apt-get install -y gdb-multiarch
RUN wget -O ~/.gdbinit-gef.py -q https://gef.blah.cat/py
RUN sed -i '1i #source ~/.gdbinit-gef.py' ~/.gdbinit
RUN sed -i '1i #source ~/peda/peda.py' ~/.gdbinit
#RUN apt-get install -y gcc-riscv64-linux-gnu binutils-riscv64-linux-gnu
RUN apt-get install -y cpio
RUN pip2 install pycrypto
RUN pip3 install pycrypto
RUN apt-get install -y telnet
RUN apt-get install -y libvte-dev qemu-utils ipxe-qemu libvdeplug-dev libfdt-dev vim git gettext g++  autoconf automake libtool  libaio1 libasound2 libbluetooth3 libbrlapi0.6 libc6 libcacard0 libfdt1 libgcc1 libglib2.0-0 libgnutls30 libjpeg8 libncurses5 libnettle6 libnuma1 libpixman-1-0 libpng12-0 libpulse0 libsasl2-2 libsdl1.2debian libseccomp2 libspice-server1  libstdc++6 libtinfo5 libusb-1.0-0 libusbredirparser1 libuuid1 libx11-6 libxen-4.6  libxenstore3.0 zlib1g qemu-system-common bridge-utils uml-utilities
RUN apt-get install -y liblzo2-dev && \
    git clone https://github.com/sviehb/jefferson.git && \
    cd jefferson && python3 setup.py install

ENV LANG=C.UTF-8
RUN chsh -s /bin/zsh

ENTRYPOINT service ssh start && sleep infinity
